services:
  db:
    image: mysql/mysql-server:latest
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_DATABASE=mysqldb
      - MYSQL_ROOT_PASSWORD=mysqlpass
    ports:
      - '3310:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    driver: local
